### ISSUE TITLE
Remove doctests

### ISSUE THREAD

**Issue by bitemyapp** [bitemyapp/fp-course#1]

**Comment by parsonsmatt** [comment]
do we want this to be "move doctests into test suite"?

**Comment by bitemyapp** [comment]
I don't think so. They made a Tasty test suite in part because of how unreliable doctests were. I think they're all duplicate between the main test suite and the doctests. The previous versions of the README seemed to imply the doctests were optional content too. Please LMK if I'm wrong about this.

**Comment by parsonsmatt** [comment]
OK. Do we want to keep them as examples and just not use doctest for it, or delete outright?

**Comment by bitemyapp** [comment]
Leave it in for now as long as it behaves itself. It had caused trouble in the past but that might actually _be_ in the past. With a separate test suite for learners to use, the ergonomic problems aren't as relevant as it's basically just the maintainer's problem.

**Comment by parsonsmatt** [comment]
The only tricky thing we might want to do is make `stack test` only run the `hspec` tests, and not the `doctest` test suite. Or maybe the `doctests` can just be an `executable` that we build and run in CI

**Comment by bitemyapp** [comment]
That's a good idea.
