### ISSUE TITLE
Weird pattern matching type error.

### ISSUE THREAD

**Issue by zeronone** [bitemyapp/fp-course#13]
I am using `intero` with following GHC version.
```
$ stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
```

While solving `FileIO.hs` the following `main` implementation gives a weird error.
```
main ::
  IO ()
main = do
  (fp :. _) <- getArgs
  run fp
```
```
      [-Wdeferred-type-errors]
     • Couldn't match type ‘[Char]’ with ‘List Char’
       Expected type: Chars
         Actual type: [Char]
     • In a stmt of a 'do' block: (fp :. _) <- getArgs
       In the expression:
         do { (fp :. _) <- getArgs;
              run fp }
       In an equation for ‘main’:
           main
             = do { (fp :. _) <- getArgs;
                    run fp }
```

While the following implementation works.
```
main ::
  IO ()
main = do
  args <- getArgs
  case args of
    Nil -> return ()
    (fp :. _) -> run fp
```

Why in the first implementation GHC infers `getArgs` as `IO [Char]`. It is not just `intero`, `stack ghci` also yields the same error. `NoImplicitPrelude` seems to be enabled by default.

`stack` version is `1.7.1`.

**Comment by bitemyapp** [comment]
`:.` is the data constructor associated with the custom list type in the course. `:` is the one that is in `Prelude` and is also the one returned by `getArgs`.

I've been thinking about how to reconcile confusing conflicts like this, but there's no bug here I do not think.

**Comment by zeronone** [comment]
@bitemyapp But I am using`:.` in both examples. Also we are using `NoImplicitPrelude` so the `getArgs` from Prelude should not be in scope. Following is the definition of `getArgs` in `Course.List`

```
getArgs :: IO (List Chars)
getArgs = P.fmap (listh . P.fmap listh) E.getArgs
```

**Comment by bitemyapp** [comment]
@zeronone I'll take a look after work today.
