### ISSUE TITLE
Pin nixpkgs

### ISSUE THREAD

**Issue by kamadorueda** [bitemyapp/fp-course#21]
I'm on Nixos, when I try to run `$ make ghci` it fails with the following message

```
STACK_YAML="stack.yaml" stack ghci course:lib
Getting project config file from STACK_YAML environment
error: attribute 'ghc802' missing, at (string):1:43
(use '--show-trace' to show detailed location information)
make: *** [Makefile:22: ghci] Error 1
```

I was looking at the source code and I found you are using an impure version of nixpkgs here:

![image](https://user-images.githubusercontent.com/47480384/135790928-804d4d64-ee35-40d1-bca0-3f9bc34f2e0d.png)

And this may be related to the failure: ghc802 not found in my system's nixpkgs?

https://nix.dev/tutorials/towards-reproducibility-pinning-nixpkgs

**Comment by bitemyapp** [comment]
I didn't implement any of the Nix stuff and I expressly made this fork for use with Stack. If I do anything about this it will be to delete any Nix code from the repository so that others are not similarly misled.

**Comment by kamadorueda** [comment]
Thanks, that's ok, sorry for the false positive
